Safer Signals and Slots
cosmoscout/cosmoscout-vr pull request #238
Opened 2021-02-10 08:44 UTC by JonasGilg

Added safeguards, that prevent a crash, when a slot is disconnected while the signal is emitting all its slots.

The slots that are disconnected while emitting will be stored and disconnected after all other slots have been called.

2021-02-10 09:06 UTC, Schneegans requested changes
Looks good - except for the one thing I mentioned below.

If you checked whether `mIsIterating` is already `true` at the beginning of the `emit*` methods, you could catch recursive emits which are also sources of crashs, I think.

2021-02-10 09:06 UTC, Schneegans commented on src/cs-utils/Signal.hpp
> +      }
Shouldn't this be cleared? E.g. like this:

```suggestion
      }
      mSlotsToDisconnect.clear();
```

2021-02-10 15:19 UTC, JonasGilg commented
Recursive calls to emit now get ignored and a warning is logged. Connecting new slots while emitting is not a problem. The standard assures the iterator is not invalidated while inserting into a map.

2021-02-11 06:50 UTC, Schneegans approved these changes

2021-02-11 08:05 UTC, merged