Improved timings
cosmoscout/cosmoscout-vr pull request #240
Opened 2021-02-25 09:06 UTC by Schneegans

This PR significantly improves the frame timing capabilities of CosmoScout VR. Here are the changes:
* The `FrameTimings` now keep track of the number of currently active ranges. This allows us to determine the current nesting level of a timing range.
* The statistics UI element now shows the ranges as they were recorded for the last-but-one frame with the appropriate nesting level. There are tooltips for detailed information.
* A triple buffer is used for the timer queries, which improves performance.
* The recording-to-file has been adapted accordingly. It now creates a set of files, one for each nesting level per CPU or GPU.
* The `FrameTimings` class is now a real singleton, before it used some hidden static variables.

![Screenshot from 2021-02-24 13-42-39](https://user-images.githubusercontent.com/829942/109126867-0e89d300-774e-11eb-9bf6-f8d93aa19ba5.png)

2021-02-25 15:50 UTC, JonasGilg commented
The UI for the Frame Timings now only displays the time for a single frame? I actually would also like a running average as we had before, since it gives a good overview of the performance, especially with more complex plugins, that might be dropping frames irregularly, like the trajectories plugin.

The current implementation is also great, since it gives really deep information about the rendered frame.

Maybe make it configurable in the UI. Have a slider for calculating the average for the last `n` frames, with `n = 1` for the current frame only. 

Or a slider to modify the running average ratio. I think previously we had a 5% to 95% ratio. Maybe you can set that with a slider and with a 100% to 0% ratio you get only the current frame.

2021-02-25 16:37 UTC, JonasGilg requested changes

2021-02-25 16:37 UTC, JonasGilg commented on plugins/csp-timings/gui/js/csp-timings.js
> +      interval = (mod == 1 ? i * 2 : i * 2 + 1) * (int + 1);
```suggestion
      interval = (mod === 1 ? i * 2 : i * 2 + 1) * (int + 1);
```

2021-02-25 16:37 UTC, JonasGilg commented on plugins/csp-timings/gui/js/csp-timings.js
> +      if (i == ticks) {
```suggestion
      if (i === ticks) {
```

2021-02-25 16:37 UTC, JonasGilg commented on plugins/csp-timings/gui/js/csp-timings.js
> +      if (i % 5 == 0) {
```suggestion
      if (i % 5 === 0) {
```

2021-02-25 16:37 UTC, JonasGilg commented on plugins/csp-timings/src/Plugin.cpp
> +        for (uint32_t i = 0; i < ranges.size(); ++i) {
This can be a range based loop.

2021-02-25 16:37 UTC, JonasGilg commented on plugins/csp-timings/src/Plugin.cpp
> +    // Compute the maximum nesting level amongst all recoreded ranges.
```suggestion
    // Compute the maximum nesting level amongst all recorded ranges.
```

2021-02-25 16:37 UTC, JonasGilg commented on plugins/csp-timings/src/Plugin.cpp
> +    auto saveRecording = [directory](std::string const&                          prefix,
```suggestion
    auto saveRecording = [&directory](std::string const&                          prefix,
```

2021-02-26 08:00 UTC, Schneegans commented on plugins/csp-timings/src/Plugin.cpp
> +        for (uint32_t i = 0; i < ranges.size(); ++i) {
Done.

2021-02-26 08:08 UTC, Schneegans commented
Implementing an average on this kind of data is close-to-impossible. The reason is that the number of ranges, their nesting level, the ordering - basically anything which is shown in the graph may completely change from one frame to another. Of course it looks oftentimes similar from one frame to the next but there is no guarantee... Implementing something which tries to match one of these datasets to the next will be really hard. 

That being said, I implemented another variant which is even better (at least in my opinion): We now have a slider in the statistics UI which lets you scroll through the last couple of frames! This way we can easily explore what took longer in the stuttering frames. What do you think?

2021-02-26 08:25 UTC, JonasGilg commented
> Implementing an average on this kind of data is close-to-impossible. The reason is that the number of ranges, their nesting level, the ordering - basically anything which is shown in the graph may completely change from one frame to another. Of course it looks oftentimes similar from one frame to the next but there is no guarantee... Implementing something which tries to match one of these datasets to the next will be really hard.
> 
> That being said, I implemented another variant which is even better (at least in my opinion): We now have a slider in the statistics UI which lets you scroll through the last couple of frames! This way we can easily explore what took longer in the stuttering frames. What do you think?

This looks great. I found a small bug though. When you scroll through the frames, before there is any data available I get the following error:
```
[E] cs-gui ............ Uncaught TypeError: Cannot read property '0' of undefined
```

2021-02-26 08:34 UTC, JonasGilg requested changes

2021-02-26 08:34 UTC, JonasGilg commented on plugins/csp-timings/gui/js/csp-timings.js
>        let int  = ~~(i / 3);
```suggestion
      let int  = Math.floor(i / 3);
```

2021-02-26 09:01 UTC, JonasGilg approved these changes

2021-02-26 09:23 UTC, merged