Simple Eclipses
cosmoscout/cosmoscout-vr pull request #277
Opened 2022-05-30 07:04 UTC by Schneegans

2022-05-30 13:13 UTC, JonasGilg commented
There seems to be an error towards the start and end of eclipses. From one second to another the shadow disappears completely.
Below are two example pictures one second after the other:
![Eclipse_2022-05-16T06-22-36](https://user-images.githubusercontent.com/9581540/170999398-cd62bb06-86c5-45ad-b583-cafca5d584cf.PNG)
![Eclipse_2022-05-16T06-22-37](https://user-images.githubusercontent.com/9581540/170999407-a80ffd05-3e29-40ab-b811-91f686cc2dcc.PNG)

If you toggle between them in an image viewer or in CosmoScout you can see, that the shadow diappears abruptly, instead of smoothly.

2022-05-30 13:23 UTC, JonasGilg commented
> If you toggle between them in an image viewer or in CosmoScout you can see, that the shadow diappears abruptly, instead of smoothly.

Another example would be 2006-03-29 12:17:51 + 12:17:52 over central Asia.

2022-05-30 18:30 UTC, Schneegans commented
Thanks for discovering this! There was indeed a bug in the CPU-side identification of potential eclipse shadow casters (the Sun had a radius of zero..). Now it should be working!

2022-05-31 09:12 UTC, JonasGilg requested changes

2022-05-31 09:12 UTC, JonasGilg commented on src/cs-core/EclipseShadowReceiver.hpp
> +#include <memory>
```suggestion
#include <glm/glm.hpp>
#include <array>
#include <memory>
```

2022-05-31 09:12 UTC, JonasGilg commented on src/cs-core/Settings.hpp
> +    /// The eclipse shadow randering mode.
```suggestion
    /// The eclipse shadow rendering mode.
```

2022-06-01 07:05 UTC, Schneegans commented on plugins/csp-atmospheres/src/Plugin.cpp
> +    auto atmosphere =
Fixed.

2022-06-01 07:42 UTC, JonasGilg approved these changes
Great work! I am really happy that this has reached the core of CosmoScout VR 🥳

2022-06-01 07:48 UTC, merged