Add more simple bodies to the solar system.
cosmoscout/cosmoscout-vr pull request #280
Opened 2022-06-01 15:20 UTC by JonasGilg

Adds **Phobos**, **Ceres**, **Vesta**, **Io**, **Enceladus**, **Tethys**, **Dione**, **Rhea** and **Iapetus** to the default config.

I limited the texture sizes to 4096x2048 px, although much larger textures are available with up to 26704x13352 px,

2022-06-01 18:40 UTC, Schneegans requested changes
This looks great! Do you plan to add more bodies in this PR or will the other bodies suggested in #279 be added later?

Anyways, it would be cool incorporate the same changes to `simple_vive.json`. AFAIK, it should be basically the same except for these keys;

```json
"sceneScale": {
    "minScale": 1,
    "maxScale": 100000000000000000,
    "closeVisualDistance": 2,
    "farVisualDistance": 5,
    "closeRealDistance": 2,
    "farRealDistance": 10000000,
    "lockWeight": 0.1,
    "trackWeight": 0.0002,
    "minObjectSize": 100000.0,
    "nearClip": 0.2,
    "minFarClip": 200.0,
    "maxFarClip": 20000.0
  },
  "enableMouseRay": true,
  "enableSensorSizeControl": false,
  "guiPosition": {
    "heightMeter": 1.8,
    "heightPixel": 1200,
    "posXMeter": 0.0,
    "posYMeter": 1.2,
    "posZMeter": -1.0,
    "rotX": 0.0,
    "rotY": 0.0,
    "rotZ": 0.0,
    "widthMeter": 2.4,
    "widthPixel": 1600
  },
```

2022-06-02 07:09 UTC, JonasGilg commented
Okay, I will include more bodies and bring the Vive-Config up-to-date.

2022-06-02 13:48 UTC, JonasGilg commented
I know added more bodies. I tried filling missing data with reasonable solid colors or gradients. It still looks strange, but better than nothing.

Lighting is now enabled by default.

For the credits file: I gave only the author names / citations, where it was required.

2022-06-02 18:34 UTC, Schneegans approved these changes

2022-06-03 07:10 UTC, merged