Ring eclipses
cosmoscout/cosmoscout-vr pull request #283
Opened 2022-06-02 08:48 UTC by Schneegans

This will need to be merged first: #280 .

2022-06-03 07:13 UTC, Schneegans commented
Shall we merge this as well? Looks good to me.

2022-06-03 07:17 UTC, JonasGilg commented
> Shall we merge this as well? Looks good to me.

Do we want to add shading to the ring first?

2022-06-03 07:44 UTC, JonasGilg requested changes

2022-06-03 07:44 UTC, JonasGilg commented on docs/changelog.md
>  * Celestial bodies can now cast eclipse shadows onto other objects. This is now used by `csp-lod-bodies`, `csp-simple-bodies` as well as by `csp-atmospheres`. For now, this is computed by approximati
```suggestion
* Celestial bodies can now cast eclipse shadows onto other objects. This is now used by `csp-lod-bodies`, `csp-simple-bodies`, `csp-rings` as well as by `csp-atmospheres`. For now, this is computed by approximating the involved bodies as spheres as well as ignoring atmospheric effects.
```

2022-06-07 12:08 UTC, JonasGilg approved these changes

2022-06-07 12:13 UTC, merged