Make compliant with the REUSE specification
cosmoscout/cosmoscout-vr pull request #300
Opened 2022-10-04 07:01 UTC by Schneegans

This makes CosmoScout VR compliant with the [REUSE Specification of the Free Software Foundation Europe](https://reuse.software/).
* It is now clear for each and every file
  * Who is the copyright holder?
  * What is the license for the file?
* There's a new CI job which enforces this.
* There's a new badge in the README to show the status.

This requires #298 to be merged first.

2022-10-04 12:59 UTC, JonasGilg commented
Is there a guideline, which file is licensed under which license? Because some config files are CC and others are MIT.

2022-10-04 13:08 UTC, Schneegans commented
> Is there a guideline for which file is licensed under which license? Because some config files are CC and others are MIT.

There should be no config files under CC-BY, however there are some under CC0.

There is no real guideline on when to choose which. However, there are two reasons due to which we may decide to publish a specific file under CC0 rather than MIT:
* The file is extremely simple. This is the case for our `.gitignore` file etc. These files do not meet a certain "threshold of originality" and are therefore not really copyrightable (see [here](https://reuse.software/faq/#what-is-copyrightable)).
* The file is very likely to be adapted by the user. For example, our scene configuration file will likely be the basis for a scene configuration file of a user. If we put it under the MIT, the user will always need to specify this which would b a pretty useless burden.

Therefore, I put very simple files and our configuration files (not the vista xml's, they actually contain complex logic) under the CC0.

2022-10-04 14:51 UTC, JonasGilg requested changes
Most change requests are adding new lines at the end if .license files.

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/callisto.jpg.license
> +SPDX-License-Identifier: CC-BY-4.0
Add newline at end of file.

```suggestion
SPDX-License-Identifier: CC-BY-4.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/ceres.jpg.license
> +SPDX-License-Identifier: CC0-1.0
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/charon.jpg.license
> +SPDX-License-Identifier: CC0-1.0
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/deimos.jpg.license
> +SPDX-License-Identifier: CC0-1.0
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/dione.jpg.license
> +SPDX-License-Identifier: CC0-1.0
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/earth.jpg.license
> +SPDX-License-Identifier: CC0-1.0
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/enceladus.jpg.license
> +SPDX-License-Identifier: CC0-1.0
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/europa.jpg.license
> +SPDX-License-Identifier: CC-BY-4.0
```suggestion
SPDX-License-Identifier: CC-BY-4.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/ganymede.jpg.license
> +SPDX-License-Identifier: CC0-1.0
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/iapetus.jpg.license
> +SPDX-License-Identifier: CC0-1.0
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/io.jpg.license
> +SPDX-License-Identifier: CC0-1.0
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/jupiter.jpg.license
> +SPDX-License-Identifier: CC-BY-3.0
```suggestion
SPDX-License-Identifier: CC-BY-3.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/mimas.jpg.license
> +SPDX-License-Identifier: CC0-1.0
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/venus.jpg.license
> +SPDX-License-Identifier: CC-BY-4.0
```suggestion
SPDX-License-Identifier: CC-BY-4.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-simple-bodies/textures/vesta.jpg.license
> +SPDX-License-Identifier: CC0-1.0
```suggestion
SPDX-License-Identifier: CC0-1.0

```

2022-10-04 14:51 UTC, JonasGilg commented on plugins/csp-wms-overlays/gui/wms_settings.html
> +</div>
```suggestion
</div>

```

2022-10-04 14:51 UTC, JonasGilg commented on test/cs-utils/filesystem.cpp
>  } // namespace cs::utils
```suggestion
} // namespace cs::utils

```

2022-10-04 14:53 UTC, JonasGilg commented on tools/New-Plugin.ps1
> +
Maybe create a test plugin to check if all files get the correct headers.

2022-10-04 16:00 UTC, Schneegans commented
Why do you want to have newlines in those files? They are auto-generated via `reuse addheader --copyright="German Aerospace Center (DLR) <cosmoscout@dlr.de>" --license="CC0-1.0" <binary file>`. It would be a bit cumbersome if we want to have those newlines...
`

2022-10-05 08:47 UTC, JonasGilg commented
> Thank you for the review! Why do we want to have newlines in those files? They are auto-generated anyways (via `reuse addheader --copyright="German Aerospace Center (DLR) <cosmoscout@dlr.de>" --license="CC0-1.0" <binary file>`). I think it would be a bit cumbersome if we want to have those newlines everywhere...

Ok, I think we can leave it then. GitHub suggested these changes, so I went with it.

2022-10-05 08:49 UTC, JonasGilg approved these changes

2022-10-05 08:50 UTC, merged