Enable OpenGL logging. Prints errors, warnings, infos, etc.
cosmoscout/cosmoscout-vr pull request #327
Opened 2023-01-26 15:59 UTC by Schneegans

2023-01-30 10:50 UTC, JonasGilg requested changes
There was already some kind of OpenGL logging here: https://github.com/cosmoscout/cosmoscout-vr/blob/main/src/cs-core/GraphicsEngine.cpp#L262
Although you had to enable it in code.

I also don't understand the functionality of the `SetupGLNode` class. This needs to be documented better. Isn't it better to do this in the GraphicsManager, since it will log all OpenGL messages?

2023-01-30 10:50 UTC, JonasGilg commented on src/cs-graphics/SetupGLNode.cpp
> +  glDebugMessageCallback(MessageCallback, static_cast<void*>(mSettings.get()));
Isn't the `Do` function part of the frame loop and called every frame? This function has to be called only once at startup.

2023-01-30 10:50 UTC, JonasGilg commented on src/cs-graphics/SetupGLNode.cpp
> +void GLAPIENTRY MessageCallback(GLenum source, GLenum type, GLuint id, GLenum severity,
You can use `else if` or early `return` to avoid unneccesary boolean evaluations.

2023-01-31 07:49 UTC, Schneegans commented
You are completely right! I actually wasn't aware of that method in the `GraphicsEngine`. :rofl: 

I'll fix this ASAP.

2023-01-31 08:40 UTC, JonasGilg approved these changes

2023-01-31 08:41 UTC, merged