LoD Body Refactoring
cosmoscout/cosmoscout-vr pull request #329
Opened 2023-02-02 16:03 UTC by Schneegans

This pull request tries to optimize the rendering performance of the `csp-lod-bodies` plugin. For this, it does the following:
* Do not stitch terrain tiles together anymore.
* Instead, draw skirt polygons around the tiles to hide any seams.
* Use a TRIANGLE_STRIP instead of TRIANGLES for the tile geometry.
* Make the resolution of the tile's image data configurable (it used to be 257*257 pixels).
* Make the resolution of the tile's elevation data configurable (it also used to be 257*257 pixels).

However, it does not:
* Properly format the shader code.
* Optimize the CPU side of things.

The main advantages are:
* We can now draw less triangles with higher resolution imagery which results in better visuals and better performance 😄
* We can use tesseleation shaders in the future.
* We have removed nearly a thousand lines of code.

The main drawbacks of this approach are:
* There is now a one-to-one mapping between image and elevation tiles. Hence, both quadtrees have the same depth. If the image channel has a much higher resolution than the elevation channel, we will request many elevation tiles with very little information content. Hence, the cache and bandwidth usage may be a bit higher.
* We can only refine a tile when image _and_ elevation data of all child nodes have been loaded. Before, it was possible to draw a node if either image _or_ elevation data was available. This can lead to somewhat slower loading times.

2023-02-14 10:16 UTC, JonasGilg requested changes

2023-02-14 10:16 UTC, JonasGilg commented on plugins/csp-lod-bodies/src/TileSourceWebMapService.hpp
> +  std::optional<std::string> loadData(glm::int64 patchIdx, int level, int x, int y);
We should use the same types everywhere.

```suggestion
  std::optional<std::string> loadData(int64_t patchIdx, int level, int x, int y);
```

2023-02-14 10:16 UTC, JonasGilg commented on plugins/csp-lod-bodies/src/TileSourceWebMapService.cpp
> +    glm::int64 patchIdx, int level, int x, int y) {
We should stick to std types if available.

```suggestion
    int64_t patchIdx, int level, int x, int y) {
```

2023-02-14 12:27 UTC, Schneegans commented on plugins/csp-lod-bodies/src/Tile.hpp
> +typename std::vector<T> const& Tile<T>::data() const {
Nothing special. It's just the definition of the member function which is declared some lines above inside the `Tile` class. Maybe I do not get your question :sweat_smile:

2023-02-14 12:32 UTC, Schneegans commented on plugins/csp-lod-bodies/src/TileRenderer.cpp
> +  locs.f1f2        = shader.GetUniformLocation("VP_f1f2");
I agree, but I think that this comes from the actual HEALPix paper. There's quite a lot of F1s and F2s in `HEALPIx.hpp` and `HEALPix.cpp`. So I would rather not change this now.

2023-02-14 12:34 UTC, Schneegans commented on plugins/csp-lod-bodies/src/TileRenderer.cpp
> +  shader.SetUniform(locs.heightInfo, averageHeight, maxHeight - minHeight);
It is used, but only to get the Tile's total min and max elevation. This could be computed much more easily :smile:

2023-02-14 12:55 UTC, Schneegans commented on plugins/csp-lod-bodies/shaders/VistaPlanetTerrainShaderUniforms.glsl
> +uniform ivec3 VP_offsetScale;
I guess the original idea was to reduce the number of uniforms which need to be set per tile. If we went for a struct, we could also use two uniforms. The latter would be even more readable. But is it worth the extra gl-call for each tile?

2023-02-14 13:15 UTC, Schneegans commented
Thanks a lot for this review! I hope that I addressed all of your concerns :smile:. Do you have any feedback regarding the chosen default values?

2023-02-14 14:34 UTC, JonasGilg commented on plugins/csp-lod-bodies/shaders/VistaPlanetTerrainShaderUniforms.glsl
> +uniform ivec3 VP_offsetScale;
Yeah, I forgot, that you have to upload each struct element individually.

2023-02-14 14:42 UTC, JonasGilg commented on plugins/csp-lod-bodies/src/Tile.hpp
> +typename std::vector<T> const& Tile<T>::data() const {
I think the `typename` before the return type can be removed.

```suggestion
std::vector<T> const& Tile<T>::data() const {
```

2023-02-14 14:42 UTC, JonasGilg commented on plugins/csp-lod-bodies/src/Tile.hpp
> +typename std::vector<T>& Tile<T>::data() {
```suggestion
std::vector<T>& Tile<T>::data() {
```

2023-02-14 14:48 UTC, JonasGilg commented
> Thanks a lot for this review! I hope that I addressed all of your concerns 😄. Do you have any feedback regarding the chosen default values?

One last comment remains. Otherwise it works great. I tried to break it with everything I could throw at it, but with the default configuration I wasn't able to find any bugs or holes in the ground. Only when I manually turned the LOD factor below 10 I was able to create situations where the planet surface had gaps between tiles, but at that point the application became useless anyways.

This is a great improvement. The render times are amazing!

2023-02-17 08:05 UTC, JonasGilg approved these changes

2023-02-17 14:30 UTC, merged