Advanced Atmospheres
cosmoscout/cosmoscout-vr pull request #330
Opened 2023-02-10 09:33 UTC by Schneegans

2023-03-08 09:22 UTC, JonasGilg commented
When the sun is over the horizon, but behind some terrain these artifacts come up. 

![image](https://user-images.githubusercontent.com/9581540/223673575-23d1a408-2da9-493e-b37f-f6f36801708d.png)

2023-03-08 09:30 UTC, JonasGilg commented
On Mars there seems to be a very hard cutoff with HDR enabled:

![image](https://user-images.githubusercontent.com/9581540/223675614-b2368d8f-8517-4939-afbc-6a7e9352c2dd.png)

2023-03-08 15:57 UTC, Schneegans commented
> On Mars there seems to be a very hard cutoff with HDR enabled:

This is due to the lack of multi-scattering in the Cosmoscout model. This should be the same as in the `main` branch.

2023-03-08 16:00 UTC, Schneegans commented
> When the sun is over the horizon, but behind some terrain these artifacts come up. 

This is a limitation of the Bruneton model. It is the result of floating point precision issues. Maybe we can improve this in a custom model in the future!

2023-03-15 10:32 UTC, JonasGilg requested changes

2023-03-15 10:32 UTC, JonasGilg commented on plugins/csp-atmospheres/src/Plugin.cpp
> +        if (mActiveAtmosphere != "") {
```suggestion
        if (!mActiveAtmosphere.empty()) {
```

2023-03-15 10:32 UTC, JonasGilg commented on plugins/csp-atmospheres/src/Plugin.cpp
> +        if (mActiveAtmosphere != "") {
```suggestion
        if (!mActiveAtmosphere.empty()) {
```

2023-03-15 10:32 UTC, JonasGilg commented on plugins/csp-atmospheres/src/Plugin.cpp
> +        if (mActiveAtmosphere != "") {
```suggestion
        if (!mActiveAtmosphere.empty()) {
```

2023-03-15 10:32 UTC, JonasGilg commented on plugins/csp-atmospheres/src/Plugin.cpp
> +        if (mActiveAtmosphere != "") {
```suggestion
        if (!mActiveAtmosphere.empty()) {
```

2023-03-15 10:32 UTC, JonasGilg commented on plugins/csp-atmospheres/src/models/bruneton/Model.cpp
> +    1.26758, 1.2367, 1.2082, 1.18737, 1.14683, 1.12362, 1.1058, 1.07124, 1.04992};
```suggestion
constexpr std::array<double, 48> SOLAR_IRRADIANCE = {1.11776, 1.14259, 1.01249, 1.14716, 1.72765,
    1.73054, 1.6887, 1.61253, 1.91198, 2.03474, 2.02042, 2.02212, 1.93377, 1.95809, 1.91686, 1.8298,
    1.8685, 1.8931, 1.85149, 1.8504, 1.8341, 1.8345, 1.8147, 1.78158, 1.7533, 1.6965, 1.68194,
    1.64654, 1.6048, 1.52143, 1.55622, 1.5113, 1.474, 1.4482, 1.41018, 1.36775, 1.34188, 1.31429,
    1.28303, 1.26758, 1.2367, 1.2082, 1.18737, 1.14683, 1.12362, 1.1058, 1.07124, 1.04992};
```

2023-03-15 10:32 UTC, JonasGilg commented on plugins/csp-atmospheres/src/models/bruneton/Model.cpp
> +    1.383e-26, 7.105e-27};
```suggestion
constexpr std::array<double, 48> OZONE_CROSS_SECTION = {1.18e-27, 2.182e-28, 2.818e-28, 6.636e-28,
    1.527e-27, 2.763e-27, 5.52e-27, 8.451e-27, 1.582e-26, 2.316e-26, 3.669e-26, 4.924e-26,
    7.752e-26, 9.016e-26, 1.48e-25, 1.602e-25, 2.139e-25, 2.755e-25, 3.091e-25, 3.5e-25, 4.266e-25,
    4.672e-25, 4.398e-25, 4.701e-25, 5.019e-25, 4.305e-25, 3.74e-25, 3.215e-25, 2.662e-25,
    2.238e-25, 1.852e-25, 1.473e-25, 1.209e-25, 9.423e-26, 7.455e-26, 6.566e-26, 5.105e-26,
    4.15e-26, 4.228e-26, 3.237e-26, 2.451e-26, 2.801e-26, 2.534e-26, 1.624e-26, 1.465e-26,
    2.078e-26, 1.383e-26, 7.105e-27};
```

2023-03-15 10:32 UTC, JonasGilg commented on plugins/csp-atmospheres/src/models/bruneton/Model.cpp
> +  ozoneDensity.push_back(internal::DensityProfileLayer(0.0, 0.0, 0.0, -1.0 / 15000.0, 8.0 / 3.0));
```suggestion
  ozoneDensity.emplace_back(25000.0, 0.0, 0.0, 1.0 / 15000.0, -2.0 / 3.0);
  ozoneDensity.emplace_back(0.0, 0.0, 0.0, -1.0 / 15000.0, 8.0 / 3.0);
```

2023-03-15 10:32 UTC, JonasGilg commented on plugins/csp-atmospheres/src/models/cosmoscout/Model.cpp
> +GLuint Model::setUniforms(GLuint program, GLuint startTextureUnit) const {
```suggestion
GLuint Model::setUniforms(GLuint /*program*/, GLuint startTextureUnit) const {
```

2023-03-17 12:15 UTC, JonasGilg approved these changes
Very nice. I am looking forward to more models being added :)

2023-03-17 12:17 UTC, merged