Improve Atmosphere Precision
cosmoscout/cosmoscout-vr pull request #338
Opened 2023-04-11 12:49 UTC by Schneegans

2023-04-14 10:30 UTC, JonasGilg commented
When navigating near the water the movement becomes jittery and with the water disabled the horizon now renders wrong:
![image](https://user-images.githubusercontent.com/9581540/232020638-075b259f-599d-48bd-975b-d59ae97d5a2e.png)

2023-04-14 12:34 UTC, JonasGilg requested changes

2023-04-14 12:34 UTC, JonasGilg commented on plugins/csp-atmospheres/src/Atmosphere.cpp
> +  std::array<GLfloat, 16> glMatV{}, glMatP{};
```suggestion
  std::array<GLfloat, 16> glMatV{};
  std::array<GLfloat, 16> glMatP{};
```

2023-04-14 14:44 UTC, Schneegans commented on plugins/csp-atmospheres/shaders/csp-atmospheres/atmosphere.frag
> +  d *= w;
I am not sure about this one. Isn't you variant an operation more? This is simply the original code by Nikita Miropolskiy.

2023-04-24 09:50 UTC, JonasGilg approved these changes

2023-04-24 09:50 UTC, JonasGilg commented on plugins/csp-atmospheres/shaders/csp-atmospheres/atmosphere.frag
> +  d *= w;
I would think, that both versions get optimized by the compiler anyways, but since this is "external" code we can keept it, like this.

2023-04-26 06:50 UTC, merged