Simple Bodies Ring Shadows
cosmoscout/cosmoscout-vr pull request #348
Opened 2023-05-20 10:10 UTC by JonasGilg

Simple bodies can now be shaded by their ring. They take the same config as the `csp-rings` plugin.

https://github.com/cosmoscout/cosmoscout-vr/assets/9581540/5f034843-47b0-4903-a982-b10da7634177

2023-05-20 10:31 UTC, JonasGilg commented on plugins/csp-simple-bodies/src/SimpleBody.cpp
> +// Calculates the shading by planetary rings. This is done in x steps:
```suggestion
// Calculates the shading by planetary rings. This is done in 3 steps:
```

2023-05-22 08:28 UTC, Schneegans requested changes
Thanks a lot! This is a simple but very nice addition. I added some remarks below.

2023-05-22 08:28 UTC, Schneegans commented on plugins/csp-simple-bodies/src/SimpleBody.cpp
> +#include "logger.hpp"
I think that this is not required, or is it?

```suggestion
```

2023-05-22 08:28 UTC, Schneegans commented on plugins/csp-simple-bodies/src/SimpleBody.cpp
> +    #endif
I think this brightness variation is not required. In fact, it leads to weird artifacts especially in non-HDR mode. Also, in the original ring shader this is not applied to the alpha channel. I think this looks better:

```suggestion
    float texPosition = (dist - uRingRadii.x) / (uRingRadii.y - uRingRadii.x);
    return 1.0 - texture(uRingTexture, vec2(texPosition, 0.5)).a;
```

2023-05-22 11:32 UTC, Schneegans commented
Looks good. However, I do not understand what Clang complains about. Do you have an idea?

2023-05-22 15:10 UTC, Schneegans approved these changes

2023-05-22 20:56 UTC, merged