Replace GLUT with SDL2
cosmoscout/cosmoscout-vr pull request #360
Opened 2023-09-06 21:45 UTC by JonasGilg

This PR replaces freeglut with SDL2 as a windowing toolkit, and input drivers. The main work is being done in Vista in the following PR: https://github.com/cosmoscout/vista/pull/24

One of the main features is a controller driver, which supports almost any controller that looks like a controller. Current feature support can be seen here: https://github.com/cosmoscout/vista/blob/feature/sdl-support/VistaCoreLibs/VistaDeviceDrivers/VistaSDL2ControllerDriver/README.md

I implemented a simple control scheme, that can be improved on in the future. Especially using the extended features of the PlayStation Controllers.

2023-11-03 12:31 UTC, Schneegans commented
Thank you very much for this impressive work! Everything seems to be working fine so far. However, when I run CosmoScout VR, I get these errors / warnings when loading the ini files:
*  **WARNING** No driver configurator for key [CONTROLLER_DB] in section of driver [SDL2CONTROLLER]
* ###ERROR### Unable to configure element type [DEFAULTWINDOW]
But everything seems to be working nonetheless. Can we get rid of these warnings?

2023-11-03 12:48 UTC, Schneegans requested changes

2023-11-03 12:48 UTC, Schneegans commented on docs/install.md
> +git submodule update --init --recursive
There are at least two other places in the `docs` directory where the `--recursive` is missing.

2023-12-05 07:49 UTC, Schneegans commented
This looks very good to me. One last thing: Could you add a corresponding entry to the changelog?

2023-12-05 08:41 UTC, JonasGilg commented
> This looks very good to me. One last thing: Could you add a corresponding entry to the changelog?

Done.

2023-12-05 08:42 UTC, Schneegans approved these changes

2023-12-05 08:43 UTC, merged