Separate atmosphere preprocessor
cosmoscout/cosmoscout-vr pull request #374
Opened 2024-06-12 06:46 UTC by Schneegans

This extracts the preprocessing code of the Bruneton atmosphere model into a separate binary. This allows us to precompute the scattering data offline and thus improve the startup time of CosmoScout VR significantly.

The precomputed data is stored in Tiff files and is available in [this repository](https://github.com/cosmoscout/atmosphere-data/tree/main) which is used as a submodule in CosmoScout VR.

2024-06-24 14:04 UTC, JonasGilg commented
I get the following error, when I try to compile with Visual Studio 2019:



```bash
[...]/plugins/csp-atmospheres/src/models/bruneton/Model.cpp(65): error C2079: "file" verwendet undefiniertes class "std::basic_ifstream<char,std::char_traits<char>>"
[...]/plugins/csp-atmospheres/src/models/bruneton/Model.cpp(65): error C2440: "Initialisierung": "std::basic_string<char,std::char_traits<char>,std::allocator<char>>" kann nicht in "int" konvertiert werden
```

2024-06-26 10:53 UTC, Schneegans commented
> I get the following error, when I try to compile with Visual Studio 2019:
> 
> ```shell
> [...]/plugins/csp-atmospheres/src/models/bruneton/Model.cpp(65): error C2079: "file" verwendet undefiniertes class "std::basic_ifstream<char,std::char_traits<char>>"
> [...]/plugins/csp-atmospheres/src/models/bruneton/Model.cpp(65): error C2440: "Initialisierung": "std::basic_string<char,std::char_traits<char>,std::allocator<char>>" kann nicht in "int" konvertiert werden
> ```

I fixed some other msvc-related issues. However, this error I do not get (also Visual Studio 2019) and the CI builds do not complain either. Do you have an idea what could be the reason?

2024-06-26 11:14 UTC, JonasGilg commented
Okay, I got it to compile. If I start it now I get the following error, when the atmospheres plugin loads:

```
[I] csp-atmospheres ... Loading plugin...
../share/resources/atmosphere-data/earth/phase.tif: Deflate compression support is not configured.
../share/resources/atmosphere-data/earth/phase.tif: Deflate compression support is not configured.
../share/resources/atmosphere-data/earth/phase.tif: Deflate compression support is not configured.
../share/resources/atmosphere-data/earth/transmittance.tif: Deflate compression support is not configured.
../share/resources/atmosphere-data/earth/transmittance.tif: Deflate compression support is not configured.
../share/resources/atmosphere-data/earth/transmittance.tif: Deflate compression support is not configured.
```

2024-06-28 08:24 UTC, Schneegans commented
Yeah, I simply use textures without compression now. Seems to be the easier approach, I guess.

2024-06-28 08:24 UTC, Schneegans commented
You'll need a `git submodule update` to fetch the new textures.

2024-07-01 14:42 UTC, JonasGilg requested changes

2024-07-15 11:33 UTC, Schneegans commented on plugins/csp-atmospheres/bruneton-preprocessor/Preprocessor.cpp
> +  float sunAngularRadiusAtEarth = 0.0046547F; // radians
This is used to compute the irradiance at the bodies position. `SOLAR_IRRADIANCE` is also hard-coded for Earth and together with the `sunAngularRadiusAtEarth`, it is corrected for any other position.

2024-07-15 11:46 UTC, merged